name: CI

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  release:
    types:
      - created

jobs:

  build_on_windows:
    runs-on: windows-latest
    env:
      EXIT: 1
    steps:
      - name: Install Erlang
        run: choco install erlang
      - name: Install Rebar3
        run: choco install rebar3
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Compile
        shell: cmd
        run: rebar3 compile
      - name: EUnit tests
        shell: cmd
        run: rebar3 eunit && echo "::set-output name=exit::1"
      - if: steps.build_on_windows.outputs.exit != '1'
        run: exit 1

