name: CI

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  release:
    types:
      - created

jobs:

  build_on_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Install Erlang/OTP
        uses: gleam-lang/setup-erlang@v1.1.3
        with:
          otp-version: "23.2"
        id: install_erlang
      - name: Compile
        shell: bash
        run: ./rebar3 compile
      - name: EUnit tests
        shell: bash
        run: ./rebar3 eunit

