name: CI

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  release:
    types:
      - created

jobs:

  build_on_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        otp: [23.3, 24.1]
    container:
      image: erlang:${{ matrix.otp }}
    steps:
      - uses: actions/checkout@v2.0.0
      - name: EUnit tests
        shell: bash
        run: rebar3 eunit

