name: quay.io

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  release:
    types:
      - created

jobs:
  quay:
    name: quay.io
    runs-on: ubuntu-latest
    container:
      image: jdrouet/docker-with-buildx:stable
      options: --privileged
      env:
        REGISTRY: 'quay.io'
        BUILD_IMAGE: 'travelping/ergw-c-node'
    steps:
    - name: Prepare
      run: |
           apk update
           apk --no-cache upgrade
           apk --no-cache add docker gcc git libc-dev libc-utils libgcc linux-headers make bash \
                              musl-dev musl-utils ncurses-dev pcre2 pkgconf scanelf wget zlib \
                              yaml-dev
    - uses: actions/checkout@v2
    - name: Build
      env:
        CI_COMMIT_REF_NAME: ${{ github.ref }}
      run: |
           docker version
           docker buildx ls
           docker buildx inspect --bootstrap




